AnimatedActionBarPlusSV =
{
    ["Default"] = 
    {
        ["@cpcharles"] = 
        {
            ["$AccountWide"] = 
            {
                ["ultGlowIntensity"] = 2,
                ["stopGlowOnPress"] = true,
                ["ultReadyIntensity"] = 2,
                ["pulseEnabled"] = true,
                ["ultBounceEnabled"] = true,
                ["animationStyle"] = "bounce",
                ["ultColorCycleEnabled"] = true,
                ["glowColor"] = 
                {
                    [4] = 1,
                    [1] = 0,
                    [2] = 1,
                    [3] = 0.9960784316,
                },
                ["ultReadyEnabled"] = true,
                ["ultGlowEnabled"] = true,
                ["pulseMode"] = "smooth",
                ["pulseDurationMS"] = 800,
                ["ultGlowColor"] = 
                {
                    [4] = 1,
                    [1] = 0,
                    [2] = 1,
                    [3] = 0.9960784316,
                },
                ["colorCycleEnabled"] = false,
                ["ultReadyMode"] = "smooth",
                ["colorCycleSecondary"] = 
                {
                    [4] = 1,
                    [1] = 1,
                    [2] = 0.1000000000,
                    [3] = 0.1000000000,
                },
                ["blinkIntervalMS"] = 250,
                ["frameResetTimeMS"] = 100,
                ["thinFrameEnabled"] = false,
                ["ultGlowDurationMS"] = 3000,
                ["ultReadyPulse"] = true,
                ["ultGlowPadding"] = 10,
                ["EU Megaserver"] = 
                {
                    ["ultGlowIntensity"] = 2.5000000000,
                    ["stopGlowOnPress"] = true,
                    ["ultReadyIntensity"] = 5,
                    ["pulseEnabled"] = false,
                    ["ultBounceEnabled"] = true,
                    ["animationStyle"] = "bounce",
                    ["ultColorCycleEnabled"] = false,
                    ["glowColor"] = 
                    {
                        [4] = 1,
                        [1] = 0,
                        [2] = 1,
                        [3] = 0.9960784316,
                    },
                    ["ultReadyEnabled"] = true,
                    ["ultGlowEnabled"] = true,
                    ["pulseMode"] = "smooth",
                    ["pulseDurationMS"] = 800,
                    ["ultGlowColor"] = 
                    {
                        [4] = 1,
                        [1] = 0,
                        [2] = 1,
                        [3] = 0.9960784316,
                    },
                    ["expireAnimStyle"] = "inherit",
                    ["colorCycleEnabled"] = false,
                    ["ultReadyMode"] = "smooth-rainbow",
                    ["colorCycleSecondary"] = 
                    {
                        [4] = 1,
                        [1] = 1,
                        [2] = 0.1000000000,
                        [3] = 0.1000000000,
                    },
                    ["blinkIntervalMS"] = 250,
                    ["ultRainbowLightness"] = 0.6700000000,
                    ["frameResetTimeMS"] = 167,
                    ["pulseMinAlpha"] = 0.7500000000,
                    ["thinFrameEnabled"] = true,
                    ["ultGlowDurationMS"] = 500,
                    ["version"] = 1,
                    ["expireGlowColor"] = 
                    {
                        [4] = 1,
                        [1] = 1,
                        [2] = 0.3000000000,
                        [3] = 0.1500000000,
                    },
                    ["expireAnimEnabled"] = true,
                    ["ultReadyPulse"] = true,
                    ["ultReadyMinAlpha"] = 0.5000000000,
                    ["ultGlowPadding"] = 10,
                    ["bounceOnProc"] = false,
                    ["__serverMigrated"] = true,
                    ["bounceEnabled"] = true,
                    ["growScale"] = 1.0700000000,
                    ["strobeIntervalMS"] = 80,
                    ["pulseMaxAlpha"] = 5,
                    ["ultReadyPulseDurMS"] = 500,
                    ["ultColorCycleSecondary"] = 
                    {
                        [4] = 1,
                        [1] = 1,
                        [2] = 0.8500000000,
                        [3] = 0.2000000000,
                    },
                    ["expireGlowEnabled"] = true,
                    ["frameAlpha"] = 1,
                    ["glowDurationMS"] = 350,
                    ["ultReadyColor"] = 
                    {
                        [4] = 1,
                        [1] = 0,
                        [2] = 1,
                        [3] = 0,
                    },
                    ["ultReadyPadding"] = 9,
                    ["ultRainbowSaturation"] = 1,
                    ["glowIntensity"] = 2,
                    ["vanillaProcGlow"] = false,
                    ["edgeStyle"] = "classic",
                    ["glowPadding"] = 10,
                    ["ultReadyBlinkIntMS"] = 250,
                    ["vanillaUltShimmer"] = false,
                    ["glowEnabled"] = true,
                    ["shrinkScale"] = 0.9300000000,
                    ["expireStrength"] = 1,
                },
                ["bounceEnabled"] = true,
                ["growScale"] = 1.0700000000,
                ["strobeIntervalMS"] = 80,
                ["version"] = 1,
                ["ultReadyPulseDurMS"] = 300,
                ["ultColorCycleSecondary"] = 
                {
                    [4] = 1,
                    [1] = 1,
                    [2] = 0,
                    [3] = 0.5803921819,
                },
                ["ultReadyMinAlpha"] = 0,
                ["bounceOnProc"] = false,
                ["glowDurationMS"] = 250,
                ["ultReadyColor"] = 
                {
                    [4] = 1,
                    [1] = 1,
                    [2] = 1,
                    [3] = 1,
                },
                ["shrinkScale"] = 0.9300000000,
                ["pulseMinAlpha"] = 0.2500000000,
                ["glowIntensity"] = 2,
                ["glowEnabled"] = true,
                ["pulseMaxAlpha"] = 1,
                ["glowPadding"] = 10,
                ["ultReadyBlinkIntMS"] = 350,
                ["vanillaUltShimmer"] = false,
                ["vanillaProcGlow"] = false,
                ["ultReadyPadding"] = 10,
                ["frameAlpha"] = 1,
            },
        },
    },
}
