HowToSunspireVariables =
{
    ["Default"] = 
    {
        ["@cpcharles"] = 
        {
            ["$AccountWide"] = 
            {
                ["debug"] = false,
                ["MeteorSelfOnly"] = true,
                ["version"] = 2,
                ["AlertSize"] = 48,
                ["hpShowPercent"] = 6,
                ["Enable"] = 
                {
                    ["Sending"] = false,
                    ["MeteorNames"] = true,
                    ["Comet"] = true,
                    ["Block"] = true,
                    ["NextFlare"] = true,
                    ["Geyser"] = true,
                    ["Shield"] = true,
                    ["NextMeteor"] = true,
                    ["LaserLokke"] = true,
                    ["PercentToFly"] = true,
                    ["HA"] = true,
                    ["GlacialFist"] = true,
                    ["hpLokke"] = true,
                    ["Spit"] = true,
                    ["Portal"] = true,
                    ["landingLokke"] = true,
                    ["Pins"] = true,
                    ["IceTomb"] = true,
                    ["Negate"] = true,
                    ["Thrash"] = true,
                    ["hpYolna"] = true,
                    ["Sound"] = true,
                    ["hpNahvii"] = true,
                    ["Atro"] = true,
                    ["SweepBreath"] = true,
                    ["Interrupt"] = true,
                    ["landingNahvii"] = true,
                    ["PowerfulSlam"] = true,
                    ["Flare"] = true,
                    ["SoulTear"] = true,
                    ["Cata"] = true,
                    ["landingYolna"] = true,
                    ["Storm"] = true,
                    ["Stonefist"] = true,
                    ["Leap"] = true,
                    ["Breath"] = true,
                    ["Wipe"] = false,
                },
                ["wipeCallLater"] = 90,
                ["timeBeforeLanding"] = 10,
                ["OffsetY"] = 
                {
                    ["SoulTear"] = 771,
                    ["Landing"] = 852.5000000000,
                    ["MeteorNames"] = -500,
                    ["Comet"] = 826,
                    ["IceTomb"] = 600,
                    ["Negate"] = 700,
                    ["Storm"] = 737,
                    ["Portal"] = 582.5000000000,
                    ["Block"] = 752,
                    ["Thrash"] = 826,
                    ["NextFlare"] = 734,
                    ["Fist"] = 741,
                    ["Leap"] = 785,
                    ["Geyser"] = 824,
                    ["Breath"] = 741,
                    ["PowerfulSlam"] = 868,
                    ["Atro"] = 633,
                    ["SweepBreath"] = 656,
                    ["Flare"] = 874,
                    ["Cata"] = 680.5000000000,
                    ["NextMeteor"] = 684,
                    ["LaserLokke"] = 740.5000000000,
                    ["MeteorName"] = 599,
                    ["Shield"] = 738,
                    ["HA"] = 701,
                    ["GlacialFist"] = -200,
                    ["Stonefist"] = -150,
                    ["Spit"] = 784,
                    ["HP"] = 853.5000000000,
                    ["Wipe"] = 583,
                },
                ["TimerSize"] = 56,
                ["FontSize"] = 40,
                ["OffsetX"] = 
                {
                    ["SoulTear"] = 1607.5000000000,
                    ["Landing"] = 1081,
                    ["MeteorNames"] = 0,
                    ["Comet"] = 1245,
                    ["IceTomb"] = 1649.5000000000,
                    ["Negate"] = 1120.5000000000,
                    ["Storm"] = 1683.5000000000,
                    ["Portal"] = 1612.5000000000,
                    ["Block"] = 1327,
                    ["Thrash"] = 1046.5000000000,
                    ["NextFlare"] = 1672.5000000000,
                    ["Fist"] = 1115,
                    ["Leap"] = 1109.5000000000,
                    ["Geyser"] = 1121.5000000000,
                    ["Breath"] = 1108.5000000000,
                    ["PowerfulSlam"] = 1128,
                    ["Atro"] = 1690,
                    ["SweepBreath"] = 1137,
                    ["Flare"] = 1405.5000000000,
                    ["Cata"] = 1133,
                    ["NextMeteor"] = 1684,
                    ["LaserLokke"] = 1365,
                    ["MeteorName"] = 1123,
                    ["Shield"] = 1116.5000000000,
                    ["HA"] = 1118.5000000000,
                    ["GlacialFist"] = 0,
                    ["Stonefist"] = 0,
                    ["Spit"] = 923.5000000000,
                    ["HP"] = 1079,
                    ["Wipe"] = 1679.5000000000,
                },
            },
        },
    },
}
