SamuraiSavedVars =
{
    ["EU Megaserver"] = 
    {
        ["@cpcharles"] = 
        {
            ["8798292077200066"] = 
            {
                ["$LastCharacterName"] = "Alyvrae Hlarahel",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = -1086,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 12,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 12,
                    ["activePoint"] = 12,
                    ["timedRelPoint"] = 12,
                    ["activeOffsetX"] = -1040.5000000000,
                    ["activeOffsetY"] = -553.5000000000,
                    ["timedOffsetY"] = -502,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292074227318"] = 
            {
                ["$LastCharacterName"] = "Zayara Ma'ri",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292070060288"] = 
            {
                ["$LastCharacterName"] = "Walk-Into-Lava",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 846.2500000000,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 12,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 6,
                    ["activePoint"] = 12,
                    ["timedRelPoint"] = 6,
                    ["activeOffsetX"] = -792.5000000000,
                    ["activeOffsetY"] = -446.2500000000,
                    ["timedOffsetY"] = -402.5000000000,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292074136144"] = 
            {
                ["$LastCharacterName"] = "Elvyndra Findthalion",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292092321114"] = 
            {
                ["$LastCharacterName"] = "Alcanist",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292081368074"] = 
            {
                ["$LastCharacterName"] = "Naya Agrn Orkinrad",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292092317832"] = 
            {
                ["$LastCharacterName"] = "Arcadeios",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292069845674"] = 
            {
                ["$LastCharacterName"] = "Ysyrae",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292082893200"] = 
            {
                ["$LastCharacterName"] = "Aegyra Nightingale",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292077991674"] = 
            {
                ["$LastCharacterName"] = "Hakim Fils-De-Forgeron",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292074347932"] = 
            {
                ["$LastCharacterName"] = "Alysiene Sidnius",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292075058708"] = 
            {
                ["$LastCharacterName"] = "Edyr Grimrest",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = -1171,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 12,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 12,
                    ["activePoint"] = 12,
                    ["timedRelPoint"] = 12,
                    ["activeOffsetX"] = -1119.5000000000,
                    ["activeOffsetY"] = -541.5000000000,
                    ["timedOffsetY"] = -505,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292077444416"] = 
            {
                ["$LastCharacterName"] = "Nirnwe Aedfaer",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292078869858"] = 
            {
                ["$LastCharacterName"] = "Ayrdaale Elsinihre",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = -1170,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = true,
                        },
                    },
                    ["activeRelPoint"] = 12,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 12,
                    ["activePoint"] = 12,
                    ["timedRelPoint"] = 12,
                    ["activeOffsetX"] = -1119.5000000000,
                    ["activeOffsetY"] = -421.5000000000,
                    ["timedOffsetY"] = -379,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292069499274"] = 
            {
                ["$LastCharacterName"] = "Daemon Feunoyr",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292079487240"] = 
            {
                ["$LastCharacterName"] = "Adryssa Fasalyn",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292078084816"] = 
            {
                ["$LastCharacterName"] = "Argili Kjisdottir",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292077050984"] = 
            {
                ["$LastCharacterName"] = "Yisith Maeshki",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292078869344"] = 
            {
                ["$LastCharacterName"] = "Urogar Orkuat",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 1181.5600585938,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 3,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 6,
                    ["activePoint"] = 3,
                    ["timedRelPoint"] = 6,
                    ["activeOffsetX"] = 1137.3199462891,
                    ["activeOffsetY"] = 499.7440185547,
                    ["timedOffsetY"] = -458.2399902344,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = false,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = true,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8798292065046456"] = 
            {
                ["$LastCharacterName"] = "Isórion",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = true,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
        },
    },
    ["NA Megaserver"] = 
    {
        ["@cpcharles"] = 
        {
            ["8796093071023819"] = 
            {
                ["$LastCharacterName"] = "Roblox vas when",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
            ["8796093064980307"] = 
            {
                ["$LastCharacterName"] = "Sieben Kugeln in den Koft",
                ["Samurai"] = 
                {
                    ["bossTimers"] = true,
                    ["debug"] = false,
                    ["timedOffsetX"] = 0,
                    ["modules"] = 
                    {
                        ["potions"] = 
                        {
                            ["renameHeroism"] = true,
                            ["renameTri"] = true,
                            ["renameVitality"] = true,
                        },
                        ["targetHealth"] = 
                        {
                            ["show"] = false,
                        },
                    },
                    ["activeRelPoint"] = 128,
                    ["version"] = 1,
                    ["hideSubtitles"] = false,
                    ["26bReset"] = true,
                    ["timedPoint"] = 1,
                    ["activePoint"] = 128,
                    ["timedRelPoint"] = 128,
                    ["activeOffsetX"] = 0,
                    ["activeOffsetY"] = -150,
                    ["timedOffsetY"] = -120,
                    ["notis"] = 
                    {
                        ["Creeper"] = true,
                        ["powerBash"] = true,
                        ["WrathofTides"] = true,
                        ["ChaurusInc"] = false,
                        ["DrainResource"] = true,
                        ["NocturnalsFavor"] = true,
                        ["ssIce"] = true,
                        ["asBossProtected"] = true,
                        ["Boulder"] = true,
                        ["IcyTeleport"] = false,
                        ["ClashofBones"] = true,
                        ["HeavyAttack"] = true,
                        ["ShockLash"] = false,
                        ["DirectCurrent"] = true,
                        ["ssGale"] = true,
                        ["StoneCurse"] = true,
                        ["Dive"] = true,
                        ["ssNegate"] = true,
                        ["transApoc"] = true,
                        ["creeperTarget"] = false,
                        ["HeavySlash"] = true,
                        ["TopplingBlow"] = true,
                        ["CrashingWave"] = true,
                        ["Bash"] = true,
                        ["ShockingSmash"] = true,
                        ["Rake"] = true,
                        ["AnvilCracker"] = true,
                        ["HeavyStrike"] = true,
                        ["creeperStun"] = false,
                        ["LavaWhip"] = true,
                        ["Chaurus"] = false,
                        ["Slam"] = true,
                        ["TakingAim"] = true,
                        ["LavaGeyser"] = true,
                        ["CrushingBlow"] = true,
                        ["UpperCut"] = true,
                    },
                },
            },
        },
    },
}
